language: java

before_script: cd ant-game

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  slack: ant-game:EcZMFzf7uCl0GBgNH2o7cQuk
